### ISSUE TITLE
GeoJSON Pemekaran Papua

### ISSUE THREAD

**Issue by GottfriedCP** [Alf-Anas/batas-administrasi-indonesia#1]
Dimana geojson provinsi-provinsi di Indonesia yang sudah mencakup pemekaran Papua? Saya cari tidak ketemu. Thank you in advance.

**Comment by Alf-Anas** [comment]
Download yang versi file shp yang sudah di kompress. Lalu convert ke GeoJSON menggunakan QGIS. Karena kalau diupload disini semuanya nggak bisa.
@GottfriedCP
